export const mockJobs = [
  {
    id: 'in-1',
    site: 'linkedin',
    job_url: 'https://www.linkedin.com/jobs/view/1',
    job_url_direct: null,
    title: 'Senior Frontend Developer',
    company: 'TechCorp Inc.',
    location: 'San Francisco, CA',
    date_posted: '2025-08-03',
    job_type: 'fulltime',
    salary_source: 'direct_data',
    interval: 'yearly',
    min_amount: 120000,
    max_amount: 160000,
    currency: 'USD',
    is_remote: false,
    job_level: 'senior',
    job_function: 'engineering',
    listing_type: null,
    emails: null,
    description:
      "We're looking for a senior frontend developer to join our team and build amazing user experiences with React and TypeScript.",
    company_industry: 'Technology',
    company_url: 'https://www.linkedin.com/company/techcorp',
    company_logo: null,
    company_url_direct: null,
    company_addresses: null,
    company_num_employees: null,
    company_revenue: null,
    company_description: '',
    skills: ['React', 'TypeScript', 'JavaScript'],
    experience_range: null,
    company_rating: null,
    company_reviews_count: null,
    vacancy_count: null,
    work_from_home_type: null,
  },
  {
    id: 'gl-2',
    site: 'glassdoor',
    job_url: 'https://www.glassdoor.com/job/2',
    job_url_direct: null,
    title: 'Product Manager',
    company: 'StartupXYZ',
    location: 'New York, NY',
    date_posted: '2025-08-04',
    job_type: 'fulltime',
    salary_source: 'direct_data',
    interval: 'yearly',
    min_amount: 100000,
    max_amount: 140000,
    currency: 'USD',
    is_remote: false,
    job_level: 'mid',
    job_function: 'product',
    listing_type: null,
    emails: null,
    description:
      'Join our product team to drive strategy and execution for our core platform. Experience with B2B SaaS preferred.',
    company_industry: 'Software',
    company_url: 'https://www.glassdoor.com/company/startupxyz',
    company_logo: null,
    company_url_direct: null,
    company_addresses: null,
    company_num_employees: null,
    company_revenue: null,
    company_description: '',
    skills: ['Product Strategy', 'SaaS', 'Analytics'],
    experience_range: null,
    company_rating: null,
    company_reviews_count: null,
    vacancy_count: null,
    work_from_home_type: null,
  },
  {
    id: 'li-3',
    site: 'linkedin',
    job_url: 'https://www.linkedin.com/jobs/view/3',
    job_url_direct: null,
    title: 'UX Designer',
    company: 'Design Studio',
    location: 'Remote',
    date_posted: '2025-08-02',
    job_type: 'contract',
    salary_source: 'direct_data',
    interval: 'yearly',
    min_amount: 80000,
    max_amount: 100000,
    currency: 'USD',
    is_remote: true,
    job_level: 'mid',
    job_function: 'design',
    listing_type: null,
    emails: null,
    description:
      'Create intuitive and beautiful user experiences for our mobile and web applications. Portfolio required.',
    company_industry: 'Design',
    company_url: 'https://www.linkedin.com/company/design-studio',
    company_logo: null,
    company_url_direct: null,
    company_addresses: null,
    company_num_employees: null,
    company_revenue: null,
    company_description: '',
    skills: ['Figma', 'User Research', 'Prototyping'],
    experience_range: null,
    company_rating: null,
    company_reviews_count: null,
    vacancy_count: null,
    work_from_home_type: null,
  },
  {
    id: 'gl-4',
    site: 'glassdoor',
    job_url: 'https://www.glassdoor.com/job/4',
    job_url_direct: null,
    title: 'Data Scientist',
    company: 'Analytics Pro',
    location: 'Austin, TX',
    date_posted: '2025-07-29',
    job_type: 'fulltime',
    salary_source: 'direct_data',
    interval: 'yearly',
    min_amount: 110000,
    max_amount: 150000,
    currency: 'USD',
    is_remote: false,
    job_level: 'senior',
    job_function: 'data',
    listing_type: null,
    emails: null,
    description:
      'Apply machine learning and statistical analysis to solve complex business problems. PhD preferred.',
    company_industry: 'Analytics',
    company_url: 'https://www.glassdoor.com/company/analytics-pro',
    company_logo: null,
    company_url_direct: null,
    company_addresses: null,
    company_num_employees: null,
    company_revenue: null,
    company_description: '',
    skills: ['Python', 'Machine Learning', 'SQL'],
    experience_range: null,
    company_rating: null,
    company_reviews_count: null,
    vacancy_count: null,
    work_from_home_type: null,
  },
  {
    id: 'li-5',
    site: 'linkedin',
    job_url: 'https://www.linkedin.com/jobs/view/5',
    job_url_direct: null,
    title: 'DevOps Engineer',
    company: 'CloudTech',
    location: 'Seattle, WA',
    date_posted: '2025-08-01',
    job_type: 'fulltime',
    salary_source: 'direct_data',
    interval: 'yearly',
    min_amount: 130000,
    max_amount: 170000,
    currency: 'USD',
    is_remote: false,
    job_level: 'senior',
    job_function: 'engineering',
    listing_type: null,
    emails: null,
    description:
      'Build and maintain scalable infrastructure on AWS. Experience with Kubernetes and Docker required.',
    company_industry: 'Cloud Technology',
    company_url: 'https://www.linkedin.com/company/cloudtech',
    company_logo: null,
    company_url_direct: null,
    company_addresses: null,
    company_num_employees: null,
    company_revenue: null,
    company_description: '',
    skills: ['AWS', 'Kubernetes', 'Docker'],
    experience_range: null,
    company_rating: null,
    company_reviews_count: null,
    vacancy_count: null,
    work_from_home_type: null,
  },
  {
    id: 'gl-6',
    site: 'glassdoor',
    job_url: 'https://www.glassdoor.com/job/6',
    job_url_direct: null,
    title: 'Marketing Manager',
    company: 'GrowthCo',
    location: 'Los Angeles, CA',
    date_posted: '2025-07-31',
    job_type: 'fulltime',
    salary_source: 'direct_data',
    interval: 'yearly',
    min_amount: 90000,
    max_amount: 120000,
    currency: 'USD',
    is_remote: false,
    job_level: 'mid',
    job_function: 'marketing',
    listing_type: null,
    emails: null,
    description:
      'Lead our digital marketing efforts and drive customer acquisition through various channels.',
    company_industry: 'Marketing',
    company_url: 'https://www.glassdoor.com/company/growthco',
    company_logo: null,
    company_url_direct: null,
    company_addresses: null,
    company_num_employees: null,
    company_revenue: null,
    company_description: '',
    skills: ['Digital Marketing', 'SEO', 'Analytics'],
    experience_range: null,
    company_rating: null,
    company_reviews_count: null,
    vacancy_count: null,
    work_from_home_type: null,
  },
];

export const navigationItems = [
  { title: 'Dashboard', icon: '📊', href: '/' },
  { title: 'Job Search', icon: '🔍', href: '/search', active: true },
  { title: 'Applications', icon: '📝', href: '/applications' },
  { title: 'Saved Jobs', icon: '❤️', href: '/saved' },
  { title: 'Profile', icon: '👤', href: '/profile' },
  { title: 'Settings', icon: '⚙️', href: '/settings' },
];

export const jobData = {
  id: 1,
  title: 'Senior Frontend Developer',
  company: 'TechCorp Inc.',
  location: 'San Francisco, CA',
  type: 'Full-time',
  salary: '$120,000 - $160,000',
  posted: '2 days ago',
  platform: 'LinkedIn',
  tags: ['React', 'TypeScript', 'JavaScript', 'CSS', 'Node.js'],
  description: `We are seeking a talented Senior Frontend Developer to join our dynamic engineering team. You will be responsible for building and maintaining high-quality web applications that serve millions of users worldwide. This role offers the opportunity to work with cutting-edge technologies and collaborate with a team of passionate developers.`,
  responsibilities: [
    'Develop and maintain responsive web applications using React and TypeScript',
    'Collaborate with UX/UI designers to implement pixel-perfect designs',
    'Optimize applications for maximum speed and scalability',
    'Write clean, maintainable, and well-documented code',
    'Participate in code reviews and mentor junior developers',
    'Work closely with backend developers to integrate APIs',
    'Stay up-to-date with the latest frontend technologies and best practices',
  ],
  qualifications: [
    '5+ years of experience in frontend development',
    'Expert knowledge of React, TypeScript, and modern JavaScript (ES6+)',
    'Strong understanding of HTML5, CSS3, and responsive design principles',
    'Experience with state management libraries (Redux, Zustand, or similar)',
    'Familiarity with testing frameworks (Jest, React Testing Library)',
    'Knowledge of build tools and bundlers (Webpack, Vite, or similar)',
    'Experience with version control systems (Git)',
    'Strong problem-solving skills and attention to detail',
  ],
  preferredQualifications: [
    'Experience with Next.js or other React frameworks',
    'Knowledge of GraphQL and Apollo Client',
    'Familiarity with cloud platforms (AWS, GCP, or Azure)',
    'Experience with CI/CD pipelines',
    'Understanding of web accessibility standards (WCAG)',
    'Previous experience in a fast-paced startup environment',
  ],
  benefits: [
    'Competitive salary and equity package',
    'Comprehensive health, dental, and vision insurance',
    'Flexible work arrangements and remote work options',
    'Professional development budget ($2,000/year)',
    'Unlimited PTO policy',
    'State-of-the-art equipment and workspace',
    'Team building events and company retreats',
  ],
};

export const companyData = {
  name: 'TechCorp Inc.',
  logo: '/placeholder.svg?height=80&width=80&text=TC',
  overview:
    'TechCorp Inc. is a leading technology company that specializes in building innovative software solutions for businesses worldwide. Founded in 2015, we have grown from a small startup to a company of over 500 employees across multiple offices.',
  culture:
    'We believe in fostering a collaborative and inclusive work environment where every team member can thrive. Our culture is built on innovation, transparency, and continuous learning. We encourage our employees to take ownership of their work and contribute to meaningful projects that impact millions of users.',
  size: '500-1000 employees',
  founded: '2015',
  industry: 'Technology',
  website: 'https://techcorp.com',
  socialMedia: {
    linkedin: 'https://linkedin.com/company/techcorp',
    twitter: 'https://twitter.com/techcorp',
    facebook: 'https://facebook.com/techcorp',
  },
  stats: {
    employees: '500+',
    offices: '5',
    countries: '3',
  },
};
